



# Chapter 1: General Introduction
## Threats on aquatic ecosystems
Ecosystems around the world are impacted by drivers of global change and freshwater environments are amongst the most degraded (Harrison et al., 2018). Freshwater ecosystems like rivers, streams, and lakes experience pervasive influences from land-use activities, introduced species, and climate change (Dudgeon et al., 2006). This is concerning as these systems disproportionately support biodiversity and ecosystem services. In lakes, the littoral zone is characterized by its exposure to sunlight, which enables photosynthesis in plants and algae, making it one of the most productive and biodiverse areas in lakes (Geist & Hawkins, 2016; Porst et al., 2019; Vadeboncoeur et al., 2011). In the shallow regions of this zone, emergent vegetation flourishes, creating essential nurseries for numerous species (Meerhoff & De Los Ángeles González-Sagrario, 2021). This vegetation significantly contributes to the energy and nutrient cycles within lake food webs. Unfortunately, lake shorelines are often heavily impacted by human activities such as hardening, introduced species like, and pollution (Strayer & Findlay, 2010; Vadeboncoeur et al., 2002). Despite their importance, there is still limited understanding of the effects of eutrophication and predation by non-native species in the littoral zone. To prevent further degradation and to bend the curve on biodiversity loss, interventions are required but these can be difficult to implement and are often expensive (Palmer et al., 2005).

## Ecosystem restoration
The UN declared 2020-2030 the decade for ecosystem restoration, with the intention of getting an hold on the degradation of ecosystems around the world (UN. General Assembly, 2019). Ecosystem restoration aims to recover an entire ecosystem including its structure, function and dynamics. Often, it focuses on enhancing the resilience of the ecosystem for future stressors. A part of ecosystem restoration is habitat restoration, this focuses on enhancing a specific habitat for a selected species. Examples of habitat restoration can include planting native vegetation or often in aquatic systems structures are added to create more variation (Banks-Leite et al., 2020; Loch et al., 2020). Enhancing habitat quality and quantity are common goals of aquatic habitat restoration, and one way this can be achieved in aquatic ecosystems is through the introduction of artificial reefs (Geist & Hawkins, 2016; Seaman, 2019). Artificial reefs can help rehabilitate degraded habitats, promote biodiversity, and support recovery of aquatic ecosystems (Kelch et al., 1999; McLean et al., 2015).

## Artificial reefs
A reef is a submerged ridge composed of rocks, corals, or other hard substrates that occur naturally and often creates biodiversity hotspots. Artificial reefs are man-made structures placed in aquatic environments to mimic natural reef or hard substrate habitats. These reefs can enhance biodiversity, fish productivity, and ecosystem resilience (Seaman, 2019). Artificial reef structures are designed to enhance habitat for organisms by creating attachment surfaces, providing shelter, and increasing habitat complexity. Artificial reefs come in various shapes, sizes, and materials, and they can be deployed in marine, lake, or river environments. The use of artificial reefs is mostly focused on marine habitats with examples including coral reef restoration and fish habitat to enhance fisheries (Bracho-Villavicencio et al., 2023; Goergen et al., 2020; Seaman, 2019). An example of an artificially modified habitat is the creation of living seawalls using sea pods in Tauranga CBD (Gillespie, 2024). The sea pods will mimic rocky tidal pools keeping water even as the tides retreats and so create habitat for algae and invertebrates. In freshwater systems artificial reefs can have similar benefits by providing fish spawning habitats and provide shelter places for various species (Creque et al., 2006).

## Freshwater crayfish
Freshwater crayfish are decapod crustaceans that form an importance component of benthic macro-invertebrate communities in a wide range of freshwater ecosystems. Freshwater crayfish are scientifically classified in the infraorder Astacidea consisting of 3 families: Astacidae, Cambaridae (also consisting of Cambaroididae), and Parastacidae (Crandall & De Grave, 2017). The Astacidae and Cambaridae are found in the northern hemisphere, whereas the Parastacidae with 15 genera are naturally found only in the southern hemisphere (Figure 1). Crayfish have a segmented exoskeleton with chelipeds (pincers) for hunting and protection. They are omnivores and play an important ecological role as scavengers, predators, and prey (Momot, 1995; Reynolds et al., 2013). They can also have a disproportionate impact on freshwater ecosystems through burrowing that changes sediment dynamics (Statzner et al., 2003), their consumption and removal of macrophytes (Nyström & Strand, 1996), and through processing organic matter as facultative detritivores (Creed & Reed, 2004). As a result, they are geomorphic agents that act as ecosystem engineers through bioturbation and contribute to nutrient cycling and trophic dynamics of food webs making them a keystone species (Crandall & Buhay, 2008; Jones et al., 2016; Nyström et al., 1996). Despite their significant role, 32% of crayfish species worldwide are threatened with extinction (Richman et al., 2015) due to numerous threats, including habitat degradation, pollution, invasive species, and overexploitation. Invasive species could be introduced non-native fish or crayfish preying on the native crayfish, competing for habitat, and spreading diseases (Danilović et al., 2022). For example, in Europe native crayfish (Astacus astacus, Austropotamobius pallipes, and A. torrentium) are susceptible and threatened by the crayfish plague fungus (Aphanomyces astaci) which is carried by many north American crayfish species (Holdich et al., 2009). Invasive crayfish also show more negative effects on the ecosystem compared to native crayfish (Vaeßen & Hollert, 2015). Therefore, conservation efforts are necessary to help native crayfish populations and their ecosystems.

 
Figure 1: Distribution of freshwater crayfish families around the world. From Fetzner, (2019).

## Kōura
Aotearoa New Zealand’s (ANZ) native biota is disproportionately made up of endemic species because of its island biogeography and isolated location (Wallis & Trewick, 2009). The two endemic species of freshwater crayfish found in ANZ are of the genus Paranephrops. These freshwater crayfish are also known by their common Māori name of kōura, although some iwi (tribes) use other names including kēwai, kēkēwai, and koeke. The two species are the northern kōura (Paranephrops planifrons White 1842) and the southern kōura (Paranephrops zealandicus White 1842). The northern kōura can be found all over the North Island and on the west side of the Southern Alps on the South Island (Figure 2). The southern kōura can be found on the eastern and southern part of the South Island and on Stewart Island.

 
Figure 2: Distribution of kōura (blue left) black line shows different in kōura species. And distribution of catfish (red right) in Aotearoa New Zealand. From: New Zealand Freshwater Fish Database (NZFFD) received on 03/04/2024. Note no catfish has yet been added in the Bay of Plenty region.

Kōura are recognized as keystone species (Collier et al., 1997) and inhabit both streams and lakes. They tend to avoid areas with low dissolved oxygen (DO < 5 mg/L) (Broughton et al., 2017) but have been observed in streams with a pH as low as 4.1 and calcium concentrations of 0.9 mg/L (Olsson et al., 2006). Kōura are sensitive to light greater than 150-205 lux and stay therefore in deeper parts of lakes or use shelters in shallower areas (Devcich, 1979). They can be found on all substrates but prefer complex habitats, such as coarse gravel or rocky substrates, which provide shelter. In streams, their highest abundance was recorded on substrates with an average length of 10 cm (Olsson, 2008). Kōura are omnivorous scavengers and consume a wide range of food resources including invertebrates (aquatic snails, chironomids, and mayflies) and detritus (Parkyn et al., 2001). During daylight hours, kōura are most vulnerable as prey for birds or other predators. Therefore, they will hide in shelters or in deeper parts of lakes during the day and move to shallower places during the night (Coffey & Clayton, 1988; Devcich, 1979). When natural substrates providing hiding places are rare, kōura can excavate tunnels or burrows to provide cover. This behaviour is only possible if the substrate is suitable like clay or pumice sand, such as in Lake Tikitapu where tunnelling behaviour has been observed. The life cycle of a kōura starts as an egg underneath the tail of its mother where it hatches to a juvenile. The juvenile stays under its mother’s tail for three weeks after which they are released. This mostly happens at less than 10 m depths in lakes (Parkyn & Kusabs, 2007). The juvenile kōura grows and moults several times and becomes mature in two to three years depending on the water temperature (Parkyn, 2000).
Kōura continue to be an important food source for Māori and are considered a taonga (treasured) species (Parkyn & Kusabs, 2007). Māori harvest kōura just like other kai (food) in specific periods of the year according to Maramataka (the lunar calendar) (Manuka Henare, n.d.). For kōura, this period is from beginning of kōanga (spring) till halfway through ngahuru (autumn). Kōura are traditionally harvested using baited traps, handpicking, or the tau kōura which uses several whakaweku (fern bundles) attached to a tāuhu by pekapeka (Figure 3). In the Rotorua Te Arawa Lakes, the kōura fisheries was very important and used for trading. The tau kōura is still used today, but mostly for routine monitoring of kōura abundance in lakes (Kusabs & Quinn, 2009). Kōura monitoring from 2005 to 2023 revealed declining kōura abundance in several of the Rotorua Te Arawa Lakes (Figure 4). This is likely the result of declining lake water quality in combination with the introduction of invasive species that include several macrophytes and brown bullhead catfish (Ameiurus nebulosus) (Kusabs et al., 2009; Kusabs, 2023b).

 
Figure 3: Two versions of the tau kōura as it can be used for harvesting kōura in a lake. © copyright Ian Kusabs.

 
Figure 4: Kōura catches in CPUE of three sites in Lake Rotoiti between 2005 and 2023. Arrow indicates completion of  the Ōhau Channel diversion wall. Kōura were caught using the tau kōura. From (Kusabs, 2023b).

## Brown bullhead catfish
The brown bullhead catfish (*Ameiurus nebulosus* Lesueur 1819) is native to North America but has been introduced for aquaculture and as a game fish all over the world. In New Zealand, 140 individuals were introduced in 1877 to Lake St John (Lake Waiatarua) (Barnes, 1996). This lake in the Auckland region has subsequently been drained but catfish have persisted. The initial goal was to introduce the channel catfish (Ictalurus punctatus) but by mistake the brown bullhead catfish was instead introduced. Since their introduction, catfish have spread throughout the upper North Island due to accidental and deliberate releases (Figure 2). This was also the case in Lake Taupō where catfish was first noticed in 1985 after illegal release (Barnes, 1996). In the Rotorua Te Arawa Lakes, a dead catfish was found at Okawa Bay in Lake Rotoiti in 2009, and sightings were reported in 2014. Surveys failed to detect catfish until 2016, when multiple catfish were found in several locations at the western end of Lake Rotoiti including Te Weta Bay. From Lake Rotoiti they spread to Lake Rotorua in 2018 through the Ōhau channel. Since 2016, routine catfish monitoring, and active catfish fishing have been carried out to reduce the impact of this invasive exotic species.
Catfish is an omnivorous benthic bottom feeder ranging from 200-455 mm and can live up to 8 years (Barnes, 1996). Spawning happens in a nest around the size of the animal made in mud or sand under vegetation and close to a rock or tree trunks for protection (Scott & Crossman, 1973). The nests are generally located in shallow areas of lakes. Females can carry 200-13000 eggs depending on their size. Catfish are comparably tolerant animals and can withstand a wide range of temperatures and low oxygen levels (Scott & Crossman, 1973). In lakes, they prefer to stay in the shallows to a depth of 17 m (Dedual, 2002). In ANZ, their diet overlaps or consist of native species leading to competition or reduction of these species. Catfish are also known predators of kōura and could therefore be responsible for the decline in kōura numbers (Figure 5) (Barnes & Hicks, 2003). Catfish can mostly be found in weedy or rocky habitats depending on the season (Barnes, 1996). In winter, most weeds are less abundant, and catfish are mostly found in rocky habitats. During autumn and spring, they can be found in both weedy and rocky areas (Barnes & Hicks, 2003). In Lake Taupō, catfish and kōura co-exist and kōura numbers have been stable. It has been suggested that the depth of the lake (mean depth 110m) allows oxygen to reach the bottom, thereby providing suitable habitat for kōura (Personal communication, Ian Kusabs, 2024).

 
Figure 5: During the monitoring of catfish in Lake Rotoiti, a dissection of a catfish revealed the tail of a kōura in its stomach.

## Study area
This research will be executed in the Rotorua Te Arawa Lakes which are located in the central of the North Island of ANZ. This area is part of the central volcanic plateau in the Bay of Plenty region and consist of multiple lakes. The lakes were formed up to 230,000 years ago by volcanic eruptions (Cole et al., 2014). The lakes still experience volcanic influence, including the eruption of Mount Tarawera in 1886, covering the area with basalt scoria and Rotomāhana Mud. The Te Arawa and Bay of Plenty region includes twelve lakes: Rotorua, Rotoiti, Rotoehu, Rotomā, Ōkataina, Ōkāreka, Tarawera, Tikitapu, Rotokākahi, Rotomāhana, Ōkaro, and Rerewhakaaitu. The Te Arawa Lakes Trust (TALT) owns the lake beds of all these lakes except for Lake Rotokākahi, which is under the guardianship of Tuhourangi and Ngāti Tumatawera iwi. TALT, in collaboration with Te Komiti Whakahaere, developed a fisheries management plan to oversee the harvest of ngā taonga in the Te Arawa Lakes (Te Arawa Lakes Trust, 2015).
These twelve lakes vary considerably in size (0.3 km² to 81 km²) and depth (13.5 m to 125 m) and exhibit diverse characteristics and water quality. Many lakes are popular for recreational boating and fishing. Most lakes contain introduced trout (Salmo trutta, Oncorhynchus mykiss). Also present are other introduced species like catfish and goldfish (morihana, Carassius auratus), as well as species endemic to ANZ like kākahi (Echyridella menziesii), kōaro (Galaxias brevipinnis), bullies (Eleotridae), and common smelt (Retropinna retropinna).
The lakes and their species are threatened by climate change, reduced water quality as a result of catchment land use, and invasive species such as hornwort (Ceratophyllum demersum) and other aquatic weeds, which often create anoxic zones in shallow areas. Current management efforts are focused on improving water quality and controlling invasive species. Strategies include dosing Lakes Rotorua and Ōkaro with aluminium phosphate to reduce phosphorus levels, spraying or harvesting invasive weeds, and implementing a catfish eradication program led by Bay of Plenty Regional Council (BoPRC) and TALT.

Table 1: Characteristics of the twelve Te Arawa Lakes.
Lake	Size (km2)	Perimeter (km)	Catchment size (km2)	Mean depth (m)	Max depth (m)	Mixing
Lake Rotorua	81	45	508	11	45	Polymictic
Lake Rotoiti	34	61	123.7	31.5	124	Monomictic
Lake Rotoehu	8	40	49.2	8	13.5	Polymictic
Lake Rotomā	11	24	27.8	36.9	83	Monomictic
Lake Ōkataina	11	29	59.8	39.4	78.5	Monomictic
Lake Ōkāreka	3	11	19.6	20	33.5	Monomictic
Lake Tarawera	41	48	143.1	50	87.5	Monomictic
Lake Tikitapu	1	5	6.2	18	27.5	Monomictic
Lake Rotokākahi	4	16	 	17.5	32	Monomictic
Lake Rotomāhana 	9	27	83.3	60	125	Monomictic
Lake Ōkaro	0.3	2	3.9	12.5	18	Monomictic
Lake Rerewhakaaitu	5	25	37	7	15.8	Polymictic

 
Figure 6: Map of twelve Te Arawa Lakes and their trophic status. NA denotes Not Available. Water quality data were obtained from the Bay of Plenty Regional Council.

## Problem statement
The kōura populations in Lake Rotoiti (since 2005) and Lakes Rotorua, Rotomā, Rotokākahi, Ōkāreka, Tarawera, and Ōkaro (since 2009) have been monitored using a tau kōura (Kusabs, Hicks, et al., 2015). This monitoring has shown a steep decline in kōura abundance in Lakes Rotorua and Rotoiti, and an absence of kōura in Lake Ōkaro. This decline is due to multiple stressors, including reduced water quality, eutrophication leading to anoxic zones in bottom waters, and a rapid growth of exotic macrophytes that obstruct movement and produce organic detritus, further exacerbating anoxic zones. Additionally, predation by catfish has significantly contributed to the decline in Lakes Rotorua and Rotoiti (Kusabs, 2023b). Current conservation and restoration efforts are insufficient to counteract these cumulative threats, and innovative solutions are urgently needed to protect and enhance kōura habitat quantity and quality. This research aims to explore the potential of artificial reefs in mitigating these stressors to enhance kōura populations in these lakes.

## Scope & Aims
This PhD research aims to identify optimal strategies for enhancing kōura populations in the Rotorua Te Arawa Lakes through the deployment of artificial reefs. When shelter availability is a limiting factor for kōura abundance, the provision of artificial reefs in the littoral zone can be expected to enhance habitat quality and quantity, providing refuge from predators and facilitating population growth. As kōura are a keystone species, supporting their populations will also benefit a range of co-occurring species that inhabit and rely on the lakes. To achieve this, I seek to determine the most effective artificial reef designs and optimal deployment locations for restoration efforts.

This research anticipates that the deployment of artificial reefs in Lake Rotoiti will yield a significant increase in kōura survival and abundance. As artificial reefs provide shelter from invasive catfish predation, kōura numbers and biomass are expected to increase on artificial reefs compared to natural habitats. Furthermore, kōura survival rates are predicted to improve on artificial reefs, and the size distribution of kōura on these reefs is expected to increase, indicating a healthy population with juveniles and sub-adults.
A key component of this PhD research is to develop artificial reef design criteria to avoid unintended consequences of poorly designed reefs. For instance, artificial reefs may inadvertently provide habitat for invasive catfish, potentially exacerbating kōura decline. Additionally, artificial reefs may fail to suppress invasive macrophytes or even enhance their growth, leading to further degradation of kōura habitat. Moreover, artificial reefs may trap sediment and debris, leading to anoxic zones and potentially replacing more suitable habitat. These outcomes will be monitored and evaluated to assess the effectiveness and optimal design criteria of artificial reefs.

## Research questions
The decline of kōura populations in the Rotorua Te Arawa Lakes has raised concerns about the long-term sustainability of this culturally and ecologically significant species. Habitat restoration using artificial reefs has been proposed as a potential solution. To address the knowledge gaps outlined above, this research aims to investigate the following questions:

1.	Can artificial rock reefs enhance kōura populations in the Rotorua Te Arawa Lakes?
2.	How can habitat restoration using artificial reefs benefit crayfish? A literature review.
3.	What are the preferred natural shoreline habitats for kōura?
4.	What artificial reefs designs are preferred by kōura?
5.	What is the effect of artificial rock reefs in the littoral zone of a small-monomictic eutrophic lake (Lake Ōkaro)?

## Thesis Structure
The five research questions will support each other to work towards the goals of this PhD (Figure 7). After this introduction, chapter 2 will describe how the first question will be answered. In chapter 2 twelve artificial reefs will be built on 4 locations in Lake Rotoiti to improve kōura habitat. The development of the reefs will be followed with seasonal monitoring. Chapter 3 comprises a literature review document the existing literature on habitat restoration using artificial reefs, with particular emphasis on the benefits for freshwater crayfish. The knowledge acquired from the literature review will be used to inform aspects of the following chapters. Chapter 4 and question 3 will determine the preferred natural shoreline habitats for kōura in the Rotorua Te Arawa Lakes. This will be done by implementing a monitoring programme to map the available natural habitats and which habitats would benefit from improvement using artificial reefs. Chapter 5 and question 4 will be assessed in a mesocosm experiment to examine the preferred artificial reef designs for kōura. Chapter 6 and question 5 will address the habitat quality of artificial reefs in Lake Ōkaro, a lake where water quality has been a limiting factor for the presence of kōura.
